/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.janelas.internalFrames;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import pacote.DBConnection;
import pacote.janelas.beans.ColaboradorBean;

/**
 *
 * @author henri
 */
public class CadColab extends javax.swing.JInternalFrame {
    
    DBConnection dbCnx;
    Connection cnx;
    ResultSet rs;
    ColaboradorBean colaboradorObj;
    
    /**
     * Creates new form CadColab
     */
    public CadColab() {
        initComponents();
        cnx = dbCnx.openConnection();
    }

    public void  runQuery(String sql) throws SQLException{
        Statement st = null;
        st = cnx.createStatement();
        st.executeUpdate(sql);
        cnx.close();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNome = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JTextField();
        jtfLogin = new javax.swing.JTextField();
        jtfsenha = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlCodAcess = new javax.swing.JLabel();
        jlTipoColab = new javax.swing.JLabel();
        jcbTipoColaborador = new javax.swing.JComboBox<>();
        jbCadastrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro Colaboradores");

        jtfNome.setText("Nome");

        jtfTelefone.setText("Telefone");

        jtfLogin.setText("login");

        jtfsenha.setText("Senha");

        jlNome.setText("Nome");

        jlTelefone.setText("Telefone");

        jlSenha.setText("Senha");

        jlCodAcess.setText("Codigo Acesso");

        jlTipoColab.setText("Tipo Colaborador");

        jcbTipoColaborador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laboratorio", "Caixa", "Vendas", "Administração" }));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlSenha)
                    .addComponent(jlTelefone)
                    .addComponent(jlNome)
                    .addComponent(jtfNome)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jtfsenha))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodAcess, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTipoColab, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipoColaborador, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                            .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome)
                            .addComponent(jlTipoColab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTipoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jlTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlCodAcess)
                        .addGap(26, 26, 26)))
                .addGap(19, 19, 19)
                .addComponent(jlSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        if(PreencherObj() == true){
            
        }
        try {
            runQuery("INSERT INTO colaboradores VALUES ('"
                    + jtfNome.getText() + "','"
                    + jtfTelefone.getText()+"',"
                    + jcbTipoColaborador.getSelectedIndex() + ",'"
                    + jtfsenha.getText() + "',"
                    + Integer.parseInt(jtfLogin.getText()) + ")");
        } catch (SQLException ex) {
            Logger.getLogger(CadColab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    public boolean PreencherObj(){
    colaboradorObj =  new ColaboradorBean();
    
    colaboradorObj.setNome(jtfNome.getText());
    colaboradorObj.setNvAcesso(jcbTipoColaborador.getSelectedIndex());
    colaboradorObj.setSenha(jtfsenha.getText());
    colaboradorObj.setTelefone(jtfTelefone.getText());
    colaboradorObj.setLogin(Integer.parseInt(jtfLogin.getText()));
    return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JComboBox<String> jcbTipoColaborador;
    private javax.swing.JLabel jlCodAcess;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTipoColab;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfsenha;
    // End of variables declaration//GEN-END:variables
}
