/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacote.janelas;
import pacote.janelas.internalFrames.CadColab;
import pacote.janelas.internalFrames.CadProd;
import pacote.janelas.internalFrames.ModClientes;
import pacote.janelas.internalFrames.ModColab;
import pacote.janelas.internalFrames.ModProd;
import pacote.janelas.internalFrames.RelClientes;
import pacote.janelas.internalFrames.RelProd;

/**
 *
 * @author henri
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    CadProd cadProduto;
    CadColab cadColab;

    ModProd modProduto;
    ModClientes modClientes;
    ModColab modColab;

    RelClientes relClientes;
    RelProd relProdutos;

    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        desktopPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmSair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmCadProd = new javax.swing.JMenuItem();
        jmCadColab = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmImpRelCliente = new javax.swing.JMenuItem();
        jmImpRelProd = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmModProd = new javax.swing.JMenuItem();
        jmModCliente = new javax.swing.JMenuItem();
        jmModColab = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jmSair.setText("Sair");
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Cadastrar");

        jmCadProd.setText("Produto");
        jmCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadProdActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadProd);

        jmCadColab.setText("Colaborador");
        jmCadColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadColabActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadColab);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Imprimir");

        jmImpRelCliente.setText("Relação de Clientes");
        jmImpRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImpRelClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jmImpRelCliente);

        jmImpRelProd.setText("Relação de Produtos");
        jmImpRelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmImpRelProdActionPerformed(evt);
            }
        });
        jMenu4.add(jmImpRelProd);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Modificar");

        jmModProd.setText("Produto");
        jmModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModProdActionPerformed(evt);
            }
        });
        jMenu5.add(jmModProd);

        jmModCliente.setText("Clientes");
        jmModCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModClienteActionPerformed(evt);
            }
        });
        jMenu5.add(jmModCliente);

        jmModColab.setText("Colaboradores");
        jmModColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModColabActionPerformed(evt);
            }
        });
        jMenu5.add(jmModColab);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //clique cadastro produto
    private void jmCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadProdActionPerformed
        cadProduto = new CadProd();
        desktopPanel.add(cadProduto);
        cadProduto.setVisible(true);
    }//GEN-LAST:event_jmCadProdActionPerformed

    //clique sair aplicação
    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jmSairActionPerformed

    //clique cadastro colaborador
    private void jmCadColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadColabActionPerformed
        cadColab = new CadColab();
        desktopPanel.add(cadColab);
        cadColab.setVisible(true);
    }//GEN-LAST:event_jmCadColabActionPerformed

    //clique de impressão de relatorio de clientes 
    private void jmImpRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImpRelClienteActionPerformed
        relClientes = new RelClientes();
        desktopPanel.add(relClientes);
        relClientes.setVisible(true);
    }//GEN-LAST:event_jmImpRelClienteActionPerformed

    //clique de impressão de relatorio de produtos (Estoque)
    private void jmImpRelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmImpRelProdActionPerformed
        relProdutos = new RelProd();
        desktopPanel.add(relProdutos);
        relProdutos.setVisible(true);
    }//GEN-LAST:event_jmImpRelProdActionPerformed

    //clique de modificação de produtos
    private void jmModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModProdActionPerformed
        modProduto = new ModProd();
        desktopPanel.add(modProduto);
        modProduto.setVisible(true);
    }//GEN-LAST:event_jmModProdActionPerformed

    //clique de modificação de clientes
    private void jmModClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModClienteActionPerformed
        modClientes = new ModClientes();
        desktopPanel.add(modClientes);
        modClientes.setVisible(true);
    }//GEN-LAST:event_jmModClienteActionPerformed

    //clique de modificação de colaborador
    private void jmModColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModColabActionPerformed
        modColab = new ModColab();
        desktopPanel.add(modColab);
        modColab.setVisible(true);
    }//GEN-LAST:event_jmModColabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCadColab;
    private javax.swing.JMenuItem jmCadProd;
    private javax.swing.JMenuItem jmImpRelCliente;
    private javax.swing.JMenuItem jmImpRelProd;
    private javax.swing.JMenuItem jmModCliente;
    private javax.swing.JMenuItem jmModColab;
    private javax.swing.JMenuItem jmModProd;
    private javax.swing.JMenuItem jmSair;
    // End of variables declaration//GEN-END:variables
}
