package pacote.janelas;

import pacote.janelas.internalFrames.*;

/**
 * @author henri
 */
public class Caixa extends javax.swing.JFrame {

    GerarCarne gerarCarne;
    ConsultarCarne conCarne;
    CxEntrada cxEn;
    CxSaida cxSa;

    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPannel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCarnê = new javax.swing.JMenu();
        jmGerarCarne = new javax.swing.JMenuItem();
        jmConsCarne = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmEntradaCx = new javax.swing.JMenuItem();
        jmSaidaCx = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPannelLayout = new javax.swing.GroupLayout(desktopPannel);
        desktopPannel.setLayout(desktopPannelLayout);
        desktopPannelLayout.setHorizontalGroup(
            desktopPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        desktopPannelLayout.setVerticalGroup(
            desktopPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuCarnê.setText("Carnê");

        jmGerarCarne.setText("Gerar Carnê");
        jmGerarCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGerarCarneActionPerformed(evt);
            }
        });
        jMenuCarnê.add(jmGerarCarne);

        jmConsCarne.setText("Consultar Carnê");
        jmConsCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsCarneActionPerformed(evt);
            }
        });
        jMenuCarnê.add(jmConsCarne);

        jMenuBar1.add(jMenuCarnê);

        jMenu2.setText("Caixa");

        jmEntradaCx.setText("Entrada");
        jmEntradaCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEntradaCxActionPerformed(evt);
            }
        });
        jMenu2.add(jmEntradaCx);

        jmSaidaCx.setText("Saida");
        jmSaidaCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSaidaCxActionPerformed(evt);
            }
        });
        jMenu2.add(jmSaidaCx);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPannel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPannel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmGerarCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGerarCarneActionPerformed
        gerarCarne = new GerarCarne();
        desktopPannel.add (gerarCarne);
        gerarCarne.setVisible(true);
    }//GEN-LAST:event_jmGerarCarneActionPerformed

    private void jmConsCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsCarneActionPerformed
        conCarne = new ConsultarCarne();
        desktopPannel.add(conCarne);
        conCarne.setVisible(true);
    }//GEN-LAST:event_jmConsCarneActionPerformed

    private void jmEntradaCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEntradaCxActionPerformed
        cxEn = new CxEntrada();
        desktopPannel.add(cxEn);
        cxEn.setVisible(true);
    }//GEN-LAST:event_jmEntradaCxActionPerformed

    private void jmSaidaCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSaidaCxActionPerformed
        cxSa = new CxSaida();
        desktopPannel.add(cxSa);
        cxSa.setVisible(true);
    }//GEN-LAST:event_jmSaidaCxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPannel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCarnê;
    private javax.swing.JMenuItem jmConsCarne;
    private javax.swing.JMenuItem jmEntradaCx;
    private javax.swing.JMenuItem jmGerarCarne;
    private javax.swing.JMenuItem jmSaidaCx;
    // End of variables declaration//GEN-END:variables
}
